"""The outline of a project's script: generated by the AI, optionally edited by a person.

Reading gives the edit if there is one, else the generated outline. Saving validates the edit
against the movie's scenes. The edit is kept apart from the generated artifact (see
`store/outline_edits.py`), so regenerating never loses it."""

from __future__ import annotations

from pydantic import BaseModel, ValidationError

from offscreen.algo.outline import BeatDraft, check_outline
from offscreen.config import AppConfig
from offscreen.domain.index import Scenes
from offscreen.domain.job import Job
from offscreen.domain.project import Project
from offscreen.domain.script import OutlineBeat, ScriptOutline
from offscreen.services.errors import InvalidInput, NotFound
from offscreen.services.jobs import GENERATE_OUTLINE, JobService
from offscreen.services.library import run_options
from offscreen.services.pipeline import Pipeline
from offscreen.stages.analysis.scenes import SCENES_FILE
from offscreen.stages.creation.outline import OUTLINE_FILE
from offscreen.store.db import Database
from offscreen.store.outline_edits import OutlineEditStore
from offscreen.store.repos import ProjectRepo


class OutlineView(BaseModel):
    outline: ScriptOutline
    edited: bool
    """True: a person's edit; False: as the AI generated it."""
    total_s: int


class OutlineService:
    def __init__(self, cfg: AppConfig, db: Database, jobs: JobService) -> None:
        self.cfg = cfg
        self.db = db
        self.jobs = jobs
        self.projects = ProjectRepo(db)
        self.edits = OutlineEditStore(cfg.data_dir)

    def generate(self, project_id: str) -> Job:
        p = self._project(project_id)
        return self.jobs.generate_outline(p.asset_id, run_options(p.options, p.id))

    def get(self, project_id: str) -> OutlineView:
        project = self._project(project_id)
        edit = self.edits.read(project_id)
        if edit is not None:
            return _view(edit, True)
        return _view(self._generated(project), False)

    def save(self, project_id: str, beats: list[OutlineBeat]) -> OutlineView:
        """Replace the beats with an edited list. Style, length target and asset stay those of
        the outline being edited."""
        project = self._project(project_id)
        current = self.edits.read(project_id) or self._generated(project)
        try:
            edited = ScriptOutline(
                asset_id=current.asset_id,
                style=current.style,
                target_duration_s=current.target_duration_s,
                beats=beats,
            )
        except ValidationError as e:
            reasons = "; ".join(str(err["msg"]) for err in e.errors())
            raise InvalidInput(f"the outline is not valid: {reasons}") from e
        problems = check_outline(
            [BeatDraft(b.beat, b.scene_refs, b.target_s) for b in beats],
            self._scene_ids(project),
            target_s=edited.target_duration_s,
            tolerance=1.0,  # a person may reshape the timing freely; the total is shown, not forced
        )
        if problems:
            raise InvalidInput("the outline breaks the rules: " + "; ".join(problems))
        self.edits.write(project_id, edited)
        return _view(edited, True)

    def reset(self, project_id: str) -> OutlineView:
        """Drop the edit and go back to the generated outline."""
        project = self._project(project_id)
        generated = self._generated(project)  # 404 before deleting anything if there is none
        self.edits.delete(project_id)
        return _view(generated, False)

    # ---- internals -------------------------------------------------------------------------
    def _pipeline(self) -> Pipeline:
        return Pipeline(self.cfg, self.jobs.providers, db=self.db)

    def _generated(self, project: Project) -> ScriptOutline:
        with self._pipeline() as p:
            artifact = p.peek(
                GENERATE_OUTLINE, project.asset_id, run_options(project.options, project.id)
            )
        if artifact is None:
            raise NotFound("the outline has not been generated yet")
        return artifact.read_model(OUTLINE_FILE, ScriptOutline)

    def _scene_ids(self, project: Project) -> list[str]:
        with self._pipeline() as p:
            artifact = p.peek(
                "analysis.scenes", project.asset_id, run_options(project.options, project.id)
            )
        if artifact is None:
            raise NotFound("the movie's scenes have not been built yet")
        return [s.id for s in artifact.read_model(SCENES_FILE, Scenes).scenes]

    def _project(self, project_id: str) -> Project:
        project = self.projects.get(project_id)
        if project is None:
            raise NotFound(f"unknown project {project_id}")
        return project


def _view(outline: ScriptOutline, edited: bool) -> OutlineView:
    return OutlineView(outline=outline, edited=edited, total_s=outline.total_s)
