/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assets
         * @description Every asset with which analysis stages are already built.
         */
        get: operations["list_assets_api_assets_get"];
        put?: never;
        /**
         * Import Asset
         * @description Register a movie. Importing the same file again returns the same asset.
         */
        post: operations["import_asset_api_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse Media
         * @description Folders and video files under the media roots (no `path`: the roots), for picking a movie.
         */
        get: operations["browse_media_api_assets_browse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Asset
         * @description The asset and which analysis stages are already built.
         */
        get: operations["get_asset_api_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Asset
         * @description Queue the analysis. Returns the job (the already active one, if there is one).
         */
        post: operations["analyze_asset_api_assets__asset_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit Character
         * @description Rename, ignore, merge or reset one character. Edits go to the revision layer; the AI
         *     output is untouched. Returns the characters as they now read.
         */
        patch: operations["edit_character_api_assets__asset_id__characters__character_id__patch"];
        trace?: never;
    };
    "/api/assets/{asset_id}/characters:build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Characters
         * @description Queue face detection, grouping into people and naming (with the analysis it needs).
         *     Returns the job (the already active one, if there is one).
         */
        post: operations["build_characters_api_assets__asset_id__characters_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/index/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index Characters
         * @description The characters with human edits applied (404 until the characters stage is built).
         */
        get: operations["index_characters_api_assets__asset_id__index_characters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/index/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index Scenes
         * @description The scenes (404 until the scenes stage is built).
         */
        get: operations["index_scenes_api_assets__asset_id__index_scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/index/shots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index Shots
         * @description Shots with keyframes, quality, description and sprite position, plus the proxy video.
         */
        get: operations["index_shots_api_assets__asset_id__index_shots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/index/story": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index Story
         * @description The story: logline, acts, turning points, ending (404 until the story stage is built).
         */
        get: operations["index_story_api_assets__asset_id__index_story_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/index/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index Transcript
         * @description The dialogue lines with their times (404 until the transcript stage is built).
         */
        get: operations["index_transcript_api_assets__asset_id__index_transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analysis Report
         * @description What the analysis cost: time and model usage per stage, and what it found.
         */
        get: operations["analysis_report_api_assets__asset_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/shots/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Shots
         * @description Shots matching a description, best first (404 until the embeddings stage is built).
         */
        get: operations["search_shots_api_assets__asset_id__shots_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Live job progress.
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description A file under the data directory (videos, keyframes, audio, ...). Supports HTTP Range, so
         *     players can seek. Nothing outside the data directory is reachable.
         */
        get: operations["get_file_api_files__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Newest first.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Log
         * @description The end of the job's log file, as plain text.
         */
        get: operations["get_job_log_api_jobs__job_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}:cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Queued jobs are canceled at once; a running job stops at its next checkpoint.
         */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}:retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Job
         * @description Only failed jobs can be retried.
         */
        post: operations["retry_job_api_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description The project, which stages are built for its options, and the finished video if any.
         */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/plan:build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Plan */
        post: operations["build_plan_api_projects__project_id__plan_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render */
        post: operations["render_api_projects__project_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/script": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Script
         * @description The generated commentary text; 404 until the script job has run.
         */
        get: operations["get_script_api_projects__project_id__script_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/script:generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Script */
        post: operations["generate_script_api_projects__project_id__script_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Act */
        Act: {
            /** Name */
            name: string;
            /** Scene Ids */
            scene_ids: string[];
            /** Summary */
            summary: string;
        };
        /** AnalysisReport */
        AnalysisReport: {
            asset: components["schemas"]["MediaAsset"];
            /** Complete */
            complete: boolean;
            counts: components["schemas"]["ReportCounts"];
            llm: components["schemas"]["LlmUsage"];
            /** Stages */
            stages: components["schemas"]["StageCost"][];
            /** Total Ms */
            total_ms: number;
        };
        /** Annotation */
        Annotation: {
            /** Message */
            message: string;
            /** Segment Id */
            segment_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "fact_check" | "rule" | "style";
        };
        /** AssetDetail */
        AssetDetail: {
            asset: components["schemas"]["MediaAsset"];
            /** Stages */
            stages: components["schemas"]["StageStatus"][];
        };
        /** AudioStream */
        AudioStream: {
            /** Channels */
            channels: number;
            /** Index */
            index: number;
            /** Language */
            language?: string | null;
            /** Sample Rate */
            sample_rate: number;
        };
        /** Character */
        Character: {
            /**
             * Aliases
             * @default []
             */
            aliases: string[];
            /** Bio */
            bio?: string | null;
            face_cluster?: components["schemas"]["FaceCluster"] | null;
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Name Source */
            name_source?: ("ai" | "human" | "tmdb") | null;
            /** Role */
            role?: string | null;
        };
        /**
         * CharacterEdit
         * @description What to change about one character; only the fields present are touched.
         */
        CharacterEdit: {
            /** Aliases */
            aliases?: string[] | null;
            /** Ignored */
            ignored?: boolean | null;
            /** Merged Into */
            merged_into?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Reset
             * @default false
             */
            reset: boolean;
        };
        /** CharactersView */
        CharactersView: {
            /** Asset Id */
            asset_id: string;
            /** Characters */
            characters: components["schemas"]["Character"][];
            /** Ignored */
            ignored: string[];
            /** Merged */
            merged: {
                [key: string]: string;
            };
            /** Named */
            named: boolean;
            /** Unmatched Edits */
            unmatched_edits: number;
        };
        /** CreateProject */
        CreateProject: {
            /** Asset Id */
            asset_id: string;
            /**
             * Name
             * @description Defaults to the asset's title.
             */
            name?: string | null;
            options?: components["schemas"]["ProjectOptions"];
        };
        /**
         * DerivedFiles
         * @description Paths relative to data_dir.
         */
        DerivedFiles: {
            /** Audio 16K */
            audio_16k?: string | null;
            /** Audio 48K */
            audio_48k?: string | null;
            /** Proxy */
            proxy?: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            }[] | null;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** FaceCluster */
        FaceCluster: {
            /** Centroid Ref */
            centroid_ref?: string | null;
            /** Size */
            size: number;
            /**
             * Thumbnails
             * @default []
             */
            thumbnails: string[];
        };
        /** ImportAsset */
        ImportAsset: {
            /**
             * Path
             * @description A movie file under one of the media roots.
             */
            path: string;
            /** Title */
            title?: string | null;
        };
        /** Job */
        Job: {
            /**
             * Attempt
             * @default 0
             */
            attempt: number;
            /** Cache Key */
            cache_key?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /**
             * Lane
             * @enum {string}
             */
            lane: "gpu" | "cpu" | "api";
            /** Log Path */
            log_path?: string | null;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Scope
             * @default {}
             */
            scope: {
                [key: string]: unknown;
            };
            /** Stage */
            stage: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "canceled";
        };
        /** LlmUsage */
        LlmUsage: {
            /**
             * Cached Tokens
             * @default 0
             */
            cached_tokens: number;
            /**
             * Calls
             * @default 0
             */
            calls: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Failed Calls
             * @default 0
             */
            failed_calls: number;
            /**
             * In Tokens
             * @default 0
             */
            in_tokens: number;
            /**
             * Out Tokens
             * @default 0
             */
            out_tokens: number;
        };
        /** MediaAsset */
        MediaAsset: {
            /** Audio */
            audio: components["schemas"]["AudioStream"][];
            /** @default {} */
            derived: components["schemas"]["DerivedFiles"];
            /** Duration Ms */
            duration_ms: number;
            /** Fingerprint */
            fingerprint: string;
            /** Id */
            id: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Source Path */
            source_path: string;
            /** Subtitles External */
            subtitles_external?: string | null;
            /** Title */
            title: string;
            video: components["schemas"]["VideoInfo"];
        };
        /** MediaEntry */
        MediaEntry: {
            /** Asset Id */
            asset_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "dir" | "file";
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Size */
            size?: number | null;
        };
        /** MediaListing */
        MediaListing: {
            /** Entries */
            entries: components["schemas"]["MediaEntry"][];
            /** Parent */
            parent: string | null;
            /** Path */
            path: string | null;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** OutlineBeat */
        OutlineBeat: {
            /** Beat */
            beat: string;
            /** Scene Refs */
            scene_refs: string[];
            /** Target S */
            target_s: number;
        };
        /** Project */
        Project: {
            /** Asset Id */
            asset_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            options?: components["schemas"]["ProjectOptions"];
        };
        /** ProjectDetail */
        ProjectDetail: {
            project: components["schemas"]["Project"];
            /** Stages */
            stages: components["schemas"]["StageStatus"][];
            /** Video */
            video: string | null;
        };
        /**
         * ProjectOptions
         * @description How the commentary is written and voiced. Stages read these; changing them changes the
         *     creative stages' cache keys, never the analysis.
         */
        ProjectOptions: {
            /**
             * Minutes
             * @default 3
             */
            minutes: number;
            /**
             * Spoil Ending
             * @default true
             */
            spoil_ending: boolean;
            /**
             * Style
             * @default neutral
             */
            style: string;
            /** Voice */
            voice?: string | null;
        };
        /**
         * Rational
         * @description Exact fraction, used for frame rates (23.976 -> 24000/1001).
         */
        Rational: {
            /** Den */
            den: number;
            /** Num */
            num: number;
        };
        /** Relation */
        Relation: {
            /** A */
            a: string;
            /** B */
            b: string;
            /** Relation */
            relation: string;
        };
        /**
         * ReportCounts
         * @description What the analysis found; None where the stage is not built (or does not exist yet).
         */
        ReportCounts: {
            /** Characters */
            characters?: number | null;
            /** Scenes */
            scenes?: number | null;
            /** Shots */
            shots?: number | null;
            /** Transcript Lines */
            transcript_lines?: number | null;
        };
        /** Scene */
        Scene: {
            /**
             * Characters
             * @default []
             */
            characters: string[];
            /** End Ms */
            end_ms: number;
            /** Id */
            id: string;
            /**
             * Importance
             * @default 0.5
             */
            importance: number;
            /**
             * Line Ids
             * @default []
             */
            line_ids: string[];
            /** Location */
            location?: string | null;
            /** Shot Ids */
            shot_ids: string[];
            /** Start Ms */
            start_ms: number;
            /** Summary */
            summary: string;
        };
        /** Scenes */
        Scenes: {
            /** Asset Id */
            asset_id: string;
            /** Scenes */
            scenes: components["schemas"]["Scene"][];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
        };
        /** Script */
        Script: {
            /**
             * Annotations
             * @default []
             */
            annotations: components["schemas"]["Annotation"][];
            /**
             * Author
             * @enum {string}
             */
            author: "ai" | "human";
            /** Id */
            id: string;
            /**
             * Outline
             * @default []
             */
            outline: components["schemas"]["OutlineBeat"][];
            params: components["schemas"]["ScriptParams"];
            /** Parent Version */
            parent_version?: number | null;
            /** Project Id */
            project_id: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Segments */
            segments: components["schemas"]["ScriptSegment"][];
            /** Version */
            version: number;
        };
        /** ScriptParams */
        ScriptParams: {
            /**
             * Language
             * @default zh
             */
            language: string;
            /**
             * Perspective
             * @default third
             * @enum {string}
             */
            perspective: "first" | "third";
            /**
             * Spoil Ending
             * @default true
             */
            spoil_ending: boolean;
            /** Style */
            style: string;
            /** Target Duration S */
            target_duration_s: number;
            /** Voice Id */
            voice_id: string;
        };
        /** ScriptSegment */
        ScriptSegment: {
            /** Beat */
            beat?: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "narration" | "original";
            /**
             * Line Refs
             * @default []
             */
            line_refs: string[];
            /**
             * Scene Refs
             * @default []
             */
            scene_refs: string[];
            /** Text */
            text: string;
        };
        /** ShotCaption */
        ShotCaption: {
            /** Action */
            action?: string | null;
            /** Caption */
            caption: string;
            /** Emotion */
            emotion?: string | null;
            /**
             * Has Onscreen Text
             * @default false
             */
            has_onscreen_text: boolean;
            /**
             * Is Credits
             * @default false
             */
            is_credits: boolean;
            /** Shot Id */
            shot_id: string;
            /**
             * Shot Size
             * @default other
             * @enum {string}
             */
            shot_size: "extreme_close_up" | "close_up" | "medium" | "wide" | "extreme_wide" | "other";
        };
        /** ShotHit */
        ShotHit: {
            /**
             * Caption
             * @default
             */
            caption: string;
            /** End Ms */
            end_ms: number;
            /** Scene Id */
            scene_id?: string | null;
            /** Score */
            score: number;
            /** Shot Id */
            shot_id: string;
            /** Similarity */
            similarity: {
                [key: string]: number;
            };
            /** Start Ms */
            start_ms: number;
            /** Thumbnail */
            thumbnail?: string | null;
        };
        /** ShotQuality */
        ShotQuality: {
            /** Brightness */
            brightness: number;
            /** Sharpness */
            sharpness: number;
        };
        /** ShotSearchResult */
        ShotSearchResult: {
            /** Hits */
            hits: components["schemas"]["ShotHit"][];
            /** Query */
            query: string;
            /**
             * Rankings
             * @description Which rankings were used: image, text.
             */
            rankings: string[];
        };
        /** ShotView */
        ShotView: {
            caption?: components["schemas"]["ShotCaption"] | null;
            /** End Ms */
            end_ms: number;
            /** Id */
            id: string;
            /** Keyframes */
            keyframes: string[];
            quality?: components["schemas"]["ShotQuality"] | null;
            sprite?: components["schemas"]["SpriteSlot"] | null;
            /** Start Ms */
            start_ms: number;
        };
        /** ShotsView */
        ShotsView: {
            /** Asset Id */
            asset_id: string;
            /** Columns */
            columns: number;
            /** Rows */
            rows: number;
            /** Sheets */
            sheets: string[];
            /** Shots */
            shots: components["schemas"]["ShotView"][];
            /** Tile Height */
            tile_height: number;
            /** Tile Width */
            tile_width: number;
            /** Video */
            video: string;
        };
        /** SpriteSlot */
        SpriteSlot: {
            /** Col */
            col: number;
            /** Row */
            row: number;
            /** Sheet */
            sheet: number;
        };
        /** StageCost */
        StageCost: {
            /** Cached */
            cached: boolean;
            /** Failed Runs */
            failed_runs: number;
            /** Last Run Ms */
            last_run_ms: number | null;
            llm: components["schemas"]["LlmUsage"];
            /** Runs */
            runs: number;
            /** Stage */
            stage: string;
            /** Total Ms */
            total_ms: number;
        };
        /** StageStatus */
        StageStatus: {
            /** Cached */
            cached: boolean;
            /** Stage */
            stage: string;
        };
        /**
         * Story
         * @description Every claim about the plot carries scene ids: the anchor against hallucination.
         */
        Story: {
            /** Acts */
            acts: components["schemas"]["Act"][];
            /** Asset Id */
            asset_id: string;
            /** Ending */
            ending?: string | null;
            /**
             * Ending Scene Ids
             * @default []
             */
            ending_scene_ids: string[];
            /** Logline */
            logline: string;
            /**
             * Relations
             * @default []
             */
            relations: components["schemas"]["Relation"][];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Synopsis */
            synopsis: string;
            /**
             * Themes
             * @default []
             */
            themes: string[];
            /**
             * Turning Points
             * @default []
             */
            turning_points: components["schemas"]["TurningPoint"][];
        };
        /** Transcript */
        Transcript: {
            /** Asset Id */
            asset_id: string;
            /** Language */
            language: string;
            /** Lines */
            lines: components["schemas"]["TranscriptLine"][];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Source */
            source: string;
        };
        /** TranscriptLine */
        TranscriptLine: {
            /** End Ms */
            end_ms: number;
            /** Id */
            id: string;
            /** Speaker */
            speaker?: string | null;
            /** Start Ms */
            start_ms: number;
            /** Text */
            text: string;
            /**
             * Words
             * @default []
             */
            words: components["schemas"]["Word"][];
        };
        /** TurningPoint */
        TurningPoint: {
            /** Scene Id */
            scene_id: string;
            /** What */
            what: string;
        };
        /** VideoInfo */
        VideoInfo: {
            /** Codec */
            codec: string;
            fps: components["schemas"]["Rational"];
            /** Height */
            height: number;
            /** Width */
            width: number;
        };
        /** Word */
        Word: {
            /** End Ms */
            end_ms: number;
            /** Start Ms */
            start_ms: number;
            /** W */
            w: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_assets_api_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetail"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    import_asset_api_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportAsset"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAsset"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    browse_media_api_assets_browse_get: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaListing"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_asset_api_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyze_asset_api_assets__asset_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    edit_character_api_assets__asset_id__characters__character_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharactersView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    build_characters_api_assets__asset_id__characters_build_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    index_characters_api_assets__asset_id__index_characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharactersView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    index_scenes_api_assets__asset_id__index_scenes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenes"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    index_shots_api_assets__asset_id__index_shots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotsView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    index_story_api_assets__asset_id__index_story_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    index_transcript_api_assets__asset_id__index_transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transcript"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analysis_report_api_assets__asset_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReport"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_shots_api_assets__asset_id__shots_search_get: {
        parameters: {
            query: {
                /** @description What to look for, in words (Chinese or English). */
                q: string;
                limit?: number;
                scene_id?: string | null;
                /** @description Shots starting at or after. */
                start_ms?: number | null;
                /** @description Shots ending at or before. */
                end_ms?: number | null;
                min_sharpness?: number | null;
                min_brightness?: number | null;
                exclude_credits?: boolean;
            };
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotSearchResult"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A Server-Sent Events stream. First a `snapshot` event whose data is `{"jobs": [Job, ...]}` (active jobs and those finished in the last minutes), then a `job` event carrying the full `Job` whenever one changes. The server closes the stream now and then; `EventSource` reconnects by itself and gets a fresh snapshot, so clients just replace jobs by id. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    get_file_api_files__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description The requested byte range(s) */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Range not satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                status?: ("queued" | "running" | "succeeded" | "failed" | "canceled") | null;
                lane?: ("gpu" | "cpu" | "api") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_job_log_api_jobs__job_id__log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/plain": string;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retry_job_api_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProject"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    build_plan_api_projects__project_id__plan_build_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    render_api_projects__project_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_script_api_projects__project_id__script_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Script"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generate_script_api_projects__project_id__script_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not allowed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
